INSERT INTO CATEGORIA(descricao) VALUES ('Curso');
INSERT INTO CATEGORIA(descricao) VALUES ('Oficina');

INSERT INTO PARTICIPANTE (nome, email) VALUES ('José Silva','jose@gmail.com');
INSERT INTO PARTICIPANTE (nome, email) VALUES ('Tiago Faria','tiago@gmail.com');
INSERT INTO PARTICIPANTE (nome, email) VALUES ('Maria do Rosário','maria@gmail.com');
INSERT INTO PARTICIPANTE (nome, email) VALUES ('Teresa Silva','teresa@gmail.com');

INSERT INTO BLOCO (inicio, fim) VALUES (PARSEDATETIME('25/09/2017 08:00:00','dd/MM/yyyy HH:mm:ss'),PARSEDATETIME('25/09/2017 11:00:00','dd/MM/yyyy HH:mm:ss'));
INSERT INTO BLOCO (inicio, fim) VALUES (PARSEDATETIME('25/09/2017 14:00:00','dd/MM/yyyy HH:mm:ss'),PARSEDATETIME('25/09/2017 18:00:00','dd/MM/yyyy HH:mm:ss'));
INSERT INTO BLOCO (inicio, fim) VALUES (PARSEDATETIME('26/09/2017 08:00:00','dd/MM/yyyy HH:mm:ss'),PARSEDATETIME('26/09/2017 11:00:00','dd/MM/yyyy HH:mm:ss'));

INSERT INTO ATIVIDADE(nome,descricao,preco,categoria_id) VALUES ('Curso de HTML', 'Aprenda HTML de forma prática', 80.00, 1);
INSERT INTO ATIVIDADE(nome,descricao,preco,categoria_id) VALUES ('Oficina de Github', 'Controle versões de seus projetos', 80.00,2);

INSERT INTO ATIVIDADE_BLOCOS (atividades_id, blocos_id) VALUES (1,1);
INSERT INTO ATIVIDADE_BLOCOS (atividades_id, blocos_id) VALUES (2,2);
INSERT INTO ATIVIDADE_BLOCOS (atividades_id, blocos_id) VALUES (2,3);

INSERT INTO ATIVIDADE_PARTICIPANTES (ATIVIDADES_ID, PARTICIPANTES_ID) VALUES (1,1);
INSERT INTO ATIVIDADE_PARTICIPANTES (ATIVIDADES_ID, PARTICIPANTES_ID) VALUES (1,2);
INSERT INTO ATIVIDADE_PARTICIPANTES (ATIVIDADES_ID, PARTICIPANTES_ID) VALUES (1,3);
INSERT INTO ATIVIDADE_PARTICIPANTES (ATIVIDADES_ID, PARTICIPANTES_ID) VALUES (2,1);
INSERT INTO ATIVIDADE_PARTICIPANTES (ATIVIDADES_ID, PARTICIPANTES_ID) VALUES (2,3);
INSERT INTO ATIVIDADE_PARTICIPANTES (ATIVIDADES_ID, PARTICIPANTES_ID) VALUES (2,4);